# This is a file with less key bindings set.
# Copy it to `$XDG_CONFIG_HOME/ov/config.yaml` or start it with `ov --config ov.yaml`.
# Thanks to hupfdule (Marco Herrn) for the less keybinding information.
#
# QuitSmall: false # Quit if the file size is smaller than the terminal size.
# IsWriteOriginal: false # Write the original content when exiting.
# BeforeWriteOriginal: 0 # Write the number of lines before the current location when exiting.
# AfterWriteOriginal: 0 # Write the number of lines after the current location when exiting.
#
# CaseSensitive: false # Case sensitive search.
# SmartCaseSensitive: false # Case sensitive search if the search string contains uppercase characters.
# RegexpSearch: false # Regular expression search.
# Incsearch: true # Incremental search.
#
# MemoryLimit: -1 # The maximum number of lines that can be loaded into memory.
# MemoryLimitFile: 100 # The maximum number of lines that can be loaded into memory when opening a file.
#
# DisableMouse: false # Disable mouse support.
# DisableColumnCycle: false # Disable cycling when moving columns.
#
# ViewMode: markdown # Default view mode.
#
# For ClipboardMethod, specify “OSC52” to copy using OSC52 (if the terminal supports it).
ClipboardMethod: "OSC52" # Clipboard method. Options: "OSC52" or other.
#
# Debug: false # Debug mode.
#
Prompt:
  Normal:
#    ShowFilename: true # Show the filename.
#    InvertColor: true # Invert the color of the prompt.
#    ProcessOfCount: true # Show the process of count.

# ShrinkChar: '…' # Characters displayed when the column is shrinking.

General:
  TabWidth: 4
  Header: 0
  AlternateRows: false
  ColumnMode: false
  LineNumMode: false
  WrapMode: true
  ColumnDelimiter: ","
  MarkStyleWidth: 1
  # Style
  # String of the color name: Foreground, Background, UnderlineColor
  # Boolean: Bold, Blink, Dim, Italic, Underline
  # Number: UnderlineStyle
  Style:
    Alternate:
        Background: "gray"
    Header:
        Bold: true
    Body:
        # Add appropriate styles here
    OverStrike:
        Bold: true
    OverLine:
        Underline: true
    LineNumber:
        Bold: true
    SearchHighlight:
        Reverse: true
    ColumnHighlight:
        Reverse: true
    MarkLine:
        Background: "darkgoldenrod"
    SectionLine:
        Background: "slateblue"
    VerticalHeader:
        # Add appropriate styles here
    Ruler:
        Background: "#333333"
        Foreground: "#CCCCCC"
        Bold: true
    HeaderBorder:
        # Add appropriate styles here
        # UnderlineStyle: 2
    SectionHeaderBorder:
        # Add appropriate styles here
        # Underline: true
        # UnderlineColor: "red"
    VerticalHeaderBorder:
        Background: "#c0c0c0"
    MultiColorHighlight:
        - Foreground: "red"
        - Foreground: "aqua"
        - Foreground: "yellow"
        - Foreground: "fuchsia"
        - Foreground: "lime"
        - Foreground: "blue"
        - Foreground: "grey"
    ColumnRainbow:
        - Foreground: "white"
        - Foreground: "crimson"
        - Foreground: "aqua"
        - Foreground: "lightsalmon"
        - Foreground: "lime"
        - Foreground: "blue"
        - Foreground: "yellowgreen"
    JumpTargetLine:
        Underline: true

# Keybind
# Special key
#   "Enter","Backspace","Tab","Backtab","Esc",
#   "Delete", "Insert",
#   "Up", "Down", "Left", "Right", "Home", "End",
#   "F1...F64"
# Modifier key
#   "ctrl", "alt", "meta", "shift"
# Connect with modifier key + key
#   "ctrl+c"
KeyBind:
    exit:
        - "Escape"
        - "q"
    cancel:
        - "ctrl+c"
    write_exit:
        - "Q"
    set_write_exit:
        - "ctrl+q"
    suspend:
        - "ctrl+z"
    sync:
        - "r"
        - "ctrl+l"
    reload:
        - "R"
        - "ctrl+r"
    watch:
        - "T"
        - "ctrl+alt+w"
    watch_interval:
        - "ctrl+w"
    follow_mode:
        - "F"
    follow_all:
        - "ctrl+a"
    follow_section:
        - "F2"
    help:
        - "h"
        - "ctrl+alt+c"
    logdoc:
        - "ctrl+alt+e"
    down:
        - "e"
        - "ctrl+e"
        - "j"
        - "J"
        - "ctrl+j"
        - "Enter"
        - "Down"
    up:
        - "y"
        - "Y"
        - "ctrl+y"
        - "k"
        - "K"
        - "ctrl+K"
        - "Up"
    top:
        - "Home"
        - "g"
        - "<"
    bottom:
        - "End"
        - ">"
        - "G"
    left:
        - "left"
    right:
        - "right"
    half_left:
        - "ctrl+left"
    half_right:
        - "ctrl+right"
    page_up:
        - "PageUp"
        - "b"
        - "alt+v"
    page_down:
        - "PageDown"
        - "ctrl+v"
        - "alt+space"
        - "f"
        - "z"
    page_half_up:
        - "u"
        - "ctrl+u"
    page_half_down:
        - "d"
        - "ctrl+d"
    section_delimiter:
        - "alt+d"
    section_start:
        - "ctrl+F3"
        - "alt+s"
    section_header_num:
        - "F7"
    hide_other:
        - "alt+-"
    next_section:
        - "space"
    last_section:
        - "9"
    previous_section:
        - "^"
    mark:
        - "m"
    remove_mark:
        - "M"
    remove_all_mark:
        - "ctrl+delete"
    next_mark:
        - "alt+>"
    previous_mark:
        - "alt+<"
    set_view_mode:
        - "p"
        - "P"
    alter_rows_mode:
        - "C"
    line_number_mode:
        - "alt+n"
    search:
        - "/"
    wrap_mode:
        - "w"
        - "W"
    column_mode:
        - "c"
    backsearch:
        - "?"
    delimiter:
        - "F8"
    header:
        - "H"
    skip_lines:
        - "ctrl+s"
    tabwidth:
        - "t"
    goto:
        - ":"
    next_search:
        - "n"
    next_backsearch:
        - "N"
    next_doc:
        - "]"
    previous_doc:
        - "["
    toggle_mouse:
        - "ctrl+alt+r"
    multi_color:
        - "."
    jump_target:
        - "alt+j"
    save_buffer:
        - "s"
    convert_type:
        - "ctrl+alt+t"
    align_format:
        - "ctrl+alt+f"
    raw_format:
        - "ctrl+alt+g"
    vertical_header:
        - "ctrl+alt+b"
    header_column:
        - "ctrl+alt+d"
    fixed_column:
        - "alt+f"
    shrink_column:
        - "alt+x"
    toggle_ruler:
        - "alt+shift+F9"
    plain_mode:
        - "ctrl+F7"
    rainbow_mode:
        - "ctrl+F4"
    close_file:
        - "ctrl+F9"
        - "ctrl+alt+s"
    width_left:
        - "ctrl+shift+left"
    width_right:
        - "ctrl+shift+right"
    begin_left:
        - "shift+Home"
    end_right:
        - "shift+End"
    column_width:
        - "alt+o"
    filter:
        - "&"
    close_doc:
        - "alt+k"
    close_all_filter:
        - "ctrl+alt+k"

    input_casesensitive:
        - "alt+c"
    input_smart_casesensitive:
        - "alt+s"
    input_incsearch:
        - "alt+i"
    input_regexp_search:
        - "alt+r"
    input_non_match:
        - "!"
    input_previous:
        - "Up"
    input_next:
        - "Down"
    input_copy:
        - "ctrl+c"
    input_paste:
        - "ctrl+v"

Mode:
  markdown:
    SectionDelimiter: "^#"
    WrapMode: true
    Style:
      SectionLine:
        Background: "blue"
  psql:
    Header: 2
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
  mysql:
    Header: 3
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
