import = ["~/.config/alacritty/colors.toml"]
live_config_reload = false

[window]
dynamic_padding = true
opacity = 0.98

[font]
size = 11.5

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "PasteSelection"
mods = "Control|Shift"
key = "S"

[[keyboard.bindings]]
action = "SpawnNewInstance"
mods = "Control"
key = "Return"
