[theme]
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "net"
device = "bond0"
format_alt = " $icon {$ip|Can't acquire IP address} "

[[block]]
block = "net"
device = "eth0"
format = "$icon"
missing_format = ""
[block.icons_overrides]
net_wired = "\uf796"

[[block]]
block = "backlight"
cycle = [50, 70, 0, 30]
invert_icons = true

[[block]]
block = "toggle"
format = " $icon "
command_state = "pidof wlsunset"
command_off = "pkill wlsunset"
command_on = "systemd-run --user ~/.local/bin/wlsunset-ipgeo"
interval = 15
[block.icons_overrides]
toggle_off = "\uf185"
toggle_on = "\uf186"
[[block.click]]
button = "right"
update = true

[[block]]
block = "battery"
format = " $icon $percentage $power $time "

[[block]]
block = "disk_space"
format = " $icon $used.eng(2,_auto,_Gi)/$total.eng(2,auto,Gi) "
warning = 50
alert = 35
alert_unit = "GB"
interval = 300
[[block.click]]
button = "right"
update = true

[[block]]
block = "bluetooth"
mac = "D8:35:28:A5:FA:F7"
format = " $icon {$percentage |}"
disconnected_format = ""

[[block]]
block = "load"
format = " $icon $1m "

[[block]]
block = "temperature"
format = " $icon "

[[block]]
block = "music"
format = " $icon { $combo.rot-str()  $prev  $play  $next |}"
hide_when_empty = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = " $icon %a %v %T "
