[theme]
theme = "dracula"

[icons]
icons = "awesome6"

[[block]]
block = "net"
device = "bond0"
format_alt = "{$ip|Can't acquire IP address}"

[[block]]
block = "net"
device = "eth0"
format = ""
icons_format = "{icon}"
hide_inactive = true
[block.icons_overrides]
net_wired = "\uf796"

[[block]]
block = "backlight"
cycle = [50, 70, 0, 30]
invert_icons = true

[[block]]
block = "battery"
format = "$percentage $power $time"

[[block]]
block = "disk_space"
format = "$used/$total"
warning = 35
alert = 20
alert_unit = "GB"
interval = 300
[[block.click]]
button = "right"
update = true

[[block]]
block = "bluetooth"
mac = "D8:35:28:A5:FA:F7"
format = "{$percentage|}"
hide_disconnected = true

[[block]]
block = "load"
format = "$1m"

[[block]]
block = "temperature"

[[block]]
block = "music"
format = "{$combo.rot-str()|} {$prev|}{$play|}{$next|}"
hide_when_empty = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %v %T"
