unlet! set_defaults_vim
source $VIMRUNTIME/defaults.vim

set ts=4 sw=4 et

set viminfofile=~/.local/state/vim/viminfo
set undodir=~/.local/state/vim/undo
set undofile
let g:netrw_home=$HOME."/.local/state/vim"

set ttymouse=sgr

let g:EditorConfig_preserve_formatoptions=1

command B GitBlame
